CUSTOM_EVENT_CUSTOM_QUEST_ADDED = 1000
CUSTOM_EVENT_CUSTOM_QUEST_REMOVED = 1001
CUSTOM_EVENT_CUSTOM_QUEST_LIST_UPDATED = 1002
CUSTOM_EVENT_CUSTOM_QUEST_ADVANCED = 1003
CUSTOM_EVENT_CUSTOM_QUEST_CONDITION_COUNTER_CHANGED = 1004
CUSTOM_EVENT_CUSTOM_LEVEL_UPDATE = 1005


CUSTOM_EVENT_QUEST_SHOW_JOURNAL_ENTRY = 2000





MENU_CATEGORY_CUSTOM_JOURNAL = 69

ZO_CATEGORY_LAYOUT_INFO[MENU_CATEGORY_CUSTOM_JOURNAL] = {
    binding = "TOGGLE_CUSTOM_JOURNAL",
    categoryName = SI_MAIN_MENU_CUSTOM_JOURNAL,

    descriptor = MENU_CATEGORY_CUSTOM_JOURNAL,
    normal = "EsoUI/Art/MainMenu/menuBar_journal_up.dds",
    pressed = "EsoUI/Art/MainMenu/menuBar_journal_down.dds",
    disabled = "EsoUI/Art/MainMenu/menuBar_journal_disabled.dds",
    highlight = "EsoUI/Art/MainMenu/menuBar_journal_over.dds",
}