--------------------
--Custom Quest Journal Scene
--------------------

CUSTOM_QUEST_JOURNAL_SCENE:AddFragmentGroup(FRAGMENT_GROUP.MOUSE_DRIVEN_UI_WINDOW)
CUSTOM_QUEST_JOURNAL_SCENE:AddFragmentGroup(FRAGMENT_GROUP.FRAME_TARGET_STANDARD_RIGHT_PANEL)
CUSTOM_QUEST_JOURNAL_SCENE:AddFragmentGroup(FRAGMENT_GROUP.PLAYER_PROGRESS_BAR_KEYBOARD_CURRENT)
CUSTOM_QUEST_JOURNAL_SCENE:AddFragment(QUEST_JOURNAL_FRAGMENT)
CUSTOM_QUEST_JOURNAL_SCENE:AddFragment(FRAME_EMOTE_FRAGMENT_JOURNAL)
CUSTOM_QUEST_JOURNAL_SCENE:AddFragment(RIGHT_BG_FRAGMENT)
CUSTOM_QUEST_JOURNAL_SCENE:AddFragment(TREE_UNDERLAY_FRAGMENT)
CUSTOM_QUEST_JOURNAL_SCENE:AddFragment(TITLE_FRAGMENT)
CUSTOM_QUEST_JOURNAL_SCENE:AddFragment(JOURNAL_TITLE_FRAGMENT)
CUSTOM_QUEST_JOURNAL_SCENE:AddFragment(CODEX_WINDOW_SOUNDS)
CUSTOM_QUEST_JOURNAL_SCENE:AddFragment(ZO_TutorialTriggerFragment:New(TUTORIAL_TRIGGER_JOURNAL_OPENED))

