-- Quest update events
CUSTOM_EVENT_CUSTOM_QUEST_ADDED = 1000
CUSTOM_EVENT_CUSTOM_QUEST_REMOVED = 1001
CUSTOM_EVENT_CUSTOM_QUEST_LIST_UPDATED = 1002
CUSTOM_EVENT_CUSTOM_QUEST_ADVANCED = 1003
CUSTOM_EVENT_CUSTOM_QUEST_CONDITION_COUNTER_CHANGED = 1004
CUSTOM_EVENT_CUSTOM_LEVEL_UPDATE = 1005

-- Player change events
CUSTOM_EVENT_PLAYER_LOOT_RECEIVE = 2000
CUSTOM_EVENT_PLAYER_MONEY_RECEIVED = 2001
CUSTOM_EVENT_PLAYER_ZONE_CHANGE = 2002
CUSTOM_EVENT_PLAYER_DEATH = 2003



CUSTOM_EVENT_QUEST_SHOW_JOURNAL_ENTRY = 3000