-- Binding names
ZO_CreateStringId("SI_BINDING_NAME_TOGGLE_CUSTOM_JOURNAL", "Custom Quest Journal")
ZO_CreateStringId("SI_BINDING_NAME_LCQ_INTERACT", "Interaction Key")
ZO_CreateStringId("SI_BINDING_NAME_LCQ_DBG", "LCQ: Debug Key")

-- Debugger
ZO_CreateStringId("LCQ_DBG_FORMAT", "|cffac30[LCQ Debug]<<1>> <<2>>|r|r")
ZO_CreateStringId("LCQ_DBG_FORMAT_0", "")
ZO_CreateStringId("LCQ_DBG_FORMAT_1", "")
ZO_CreateStringId("LCQ_DBG_FORMAT_2", "|cc40000 [Critical]")
ZO_CreateStringId("LCQ_DBG_FORMAT_3", "|cff1c1c [Error]")
ZO_CreateStringId("LCQ_DBG_FORMAT_4", "")
ZO_CreateStringId("LCQ_DBG_FORMAT_5", "|cff9d00 [Warning]")
ZO_CreateStringId("LCQ_DBG_FORMAT_6", "|c0fb800 [Info]")
ZO_CreateStringId("LCQ_DBG_FORMAT_7", "|c00b5b5 [Verbose]")
ZO_CreateStringId("LCQ_DBG_FORMAT_8", "|c0081b8 [Debug]")

-- Journal
ZO_CreateStringId("LCQ_MAIN_MENU_CUSTOM_JOURNAL", "Journal II")
ZO_CreateStringId("LCQ_JOURNAL_CUSTOM_QUEST_MENU_HEADER", "Custom Quests")
ZO_CreateStringId("LCQ_QUESTS_CURRENT", "Quests: |cffffff<<1>>|r")

ZO_CreateStringId("LCQ_ADDON_CATEGORY", "Custom Quest Packs")
ZO_CreateStringId("LCQ_QUEST_COMPLETED_CATEGORY", GetString(SI_ACHIEVEMENTS_TOOLTIP_COMPLETE))

-- Mail
ZO_CreateStringId("LCQ_MAIL_CUSTOM_MAIL_HEADER", "Custom Quest Mail (<<1>>)")
ZO_CreateStringId("LCQ_MAIL_NO_CUSTOM_MAIL_HEADER", "Custom Quest Mail")
ZO_CreateStringId("LCQ_MAIL_NO_CUSTOM_MAIL_ENTRY", "You have no custom quest mail.")
ZO_CreateStringId("LCQ_MAIL_CUSTOM_MAIL_BODY", "<<1>>\n\n – Generated by LCQ for <<<2>>>")