-- Binding names
ZO_CreateStringId("SI_BINDING_NAME_TOGGLE_CUSTOM_JOURNAL", "Custom Quest Journal")
ZO_CreateStringId("SI_BINDING_NAME_LCQ_INTERACT", "Interaction Key")
ZO_CreateStringId("SI_BINDING_NAME_LCQ_DBG", "LCQ: Debug Key")

-- Journal
ZO_CreateStringId("LCQ_MAIN_MENU_CUSTOM_JOURNAL", "Journal II")
ZO_CreateStringId("LCQ_JOURNAL_CUSTOM_QUEST_MENU_HEADER", "Custom Quests")
ZO_CreateStringId("LCQ_QUESTS_CURRENT", "Quests: |cffffff<<1>>|r")

ZO_CreateStringId("LCQ_ADDON_CATEGORY", "Custom Quest Packs")
ZO_CreateStringId("LCQ_QUEST_COMPLETED_CATEGORY", GetString(SI_ACHIEVEMENTS_TOOLTIP_COMPLETE))

-- Mail
ZO_CreateStringId("LCQ_MAIL_CUSTOM_MAIL_HEADER", "Custom Quest Mail (<<1>>)")
ZO_CreateStringId("LCQ_MAIL_NO_CUSTOM_MAIL_HEADER", "Custom Quest Mail")
ZO_CreateStringId("LCQ_MAIL_NO_CUSTOM_MAIL_ENTRY", "You have no custom quest mail.")
ZO_CreateStringId("LCQ_MAIL_CUSTOM_MAIL_BODY", "<<1>>\n\n – Generated by LCQ for <<<2>>>")